include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_final_fields: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_constructors_over_static_methods: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_await_in_return: true
    depend_on_referenced_packages: false
    always_use_package_imports: false
    avoid_positional_boolean_parameters: false
    unreachable_from_main: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '*/generated/**'
    - '**/*.g.dart'
    - '**/*.config.dart'
    - 'submodules'
    - 'test/**'
