name: bsuir_schedule
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  infinite_scroll_pagination: ^4.0.0
  injectable: 2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  openapi_generator_annotations: ^5.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  analyzer: ^5.13.0 # https://github.com/petercinibulk/envied/issues/89
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.4.1
  intl_utils: ^2.8.0
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter_gen:
  enabled: true
  outputs:
    package_parameter_enabled: false
    style: dot-delimiter
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  fonts:
    enabled: true

#  colors:
#    enabled: true
#    inputs:
#      - assets/colors/colors.xml

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Raleway Bold w700
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Raleway Extra Bold w800
      fonts:
        - asset: assets/fonts/Raleway-ExtraBold.ttf
    - family: Raleway Medium w500
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: Raleway Regular w400
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Raleway Semi Bold w600
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
